version: '3.5'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
    - "8080:80"
    volumes:
      - /mnt/ssd/:/srv
      - /home/ubuntu/data/filebrowser/filebrowser.db:/database/filebrowser.db
      - /home/ubuntu/data/filebrowser/filebrowser.json:/config/settings.json
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
networks:
  default:
      name: public_facing
      external: true
