version: '3'
services:
  nginx_pm:
    #earlier: 2.9.19
    image: 'jc21/nginx-proxy-manager:2.9.19'
    container_name: nginx_pm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_pm_data:/data
      - nginx_pm_letsencrypt:/etc/letsencrypt
#      - ./_hsts.conf:/app/templates/_hsts.conf:ro
networks:
  default:
      name: public_facing
volumes:
  nginx_pm_data:
  nginx_pm_letsencrypt:
