version: "3.7"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/ubuntu/data/jackett/config:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
      - flaresolverr
    networks:
      - public_facing

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/ubuntu/data/radarr/config:/config
      - /mnt/ssd/movies:/movies
      - /mnt/ssd/torrent-download/:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - jackett
    networks:
      - public_facing

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/ubuntu/data/sonarr/config:/config
      - /mnt/ssd/torrent-download/:/downloads
      - /mnt/ssd/series:/series
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - jackett
    networks:
      - public_facing

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info #optional
      - TZ=Asia/Kolkata
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - public_facing

# Uncomment if you want to use Overseerr
# Note: Overseerr is for Plex and Jellyseerr is for Jellyfin.
# If you are using Jellyfin, use Jellyseerr instead of Overseerr.
  # overseerr:
  #   image: lscr.io/linuxserver/overseerr:latest
  #   container_name: overseerr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Kolkata
  #   volumes:
  #     - /home/ubuntu/data/overseerr/config:/config
  #   ports:
  #     - 5055:5055
  #   restart: unless-stopped
  #   networks:
  #     - public_facing

  # jellyseerr: 
  #   image: fallenbagel/jellyseerr:latest 
  #   container_name: jellyseerr 
  #   hostname: jellyseerr 
  #   user: 1000:1000 
  #   environment: 
  #     - LOG_LEVEL=debug
  #     - TZ=Asia/Kolkata
  #   ports: 
  #     - 5055:5055 
  #   volumes: 
  #     - /home/ubuntu/data/overseerr/:/app/config/
  #   depends_on: 
  #     - sonarr 
  #     - radarr 
  #   restart: unless-stopped 
  #   networks: 
  #     - public_facing 

networks:
  public_facing:
    external: true
