version: "3.7"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000 # User id
      - PGID=1000 # Group id
      - TZ=Asia/Kolkata # Your current timezone
    volumes:
      - /home/ubuntu/data/transmission:/config # Change this to your docker config folder
      - /mnt/ssd/torrent-download/:/downloads # Change this to your download folder
    ports:
      - 9092:9091 # Web UI port
      - 51413:51413 # Torrent port (TCP)
      - 51413:51413/udp # Torrent port (UDP)
    restart: unless-stopped # This makes sure that the application restarts when it crashes
networks:
  default:
      name: public_facing
      external: true